### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by johanos1** [aidotse/PASEOS#52]
# Feature
## Desired Behavior / Functionality
Allow users to take control over the actor by offering an interactive mode accessible via the command line.

An example:
```
Initiate PASEOS
Loop
  Discover peers on the network
  Communicate with peers

  **After time t, user inputs the following:**
    Register "malfunctioning battery"
    Perform "malfunctioning battery"
```
After the user has performed the activity, the battery may have a lower capacity and, hence, the other activities must adapt to the new constraints.

Potential use cases for this is:
* Simulate a satellite update
* Trigger events on demand, e.g., errors in hardware 
* Debugging purposes to test out functionality
* Debugging purposes to test robustness of the simulator

## What Needs to Be Done
Implement input-output functionality for PASEOS to register/perform activities on the fly.
PASEOS would need to listen for user inputs to register and/or perform activities.

## How Can It Be Tested
Write tests that register/perform activities after PASEOS has been running for a while by using the I/O functionality.

**Comment by gomezzz** [comment]
Can you elaborate a bit more what you would want to have? I don't get it

**Comment by johanos1** [comment]
Is it clear now?

**Comment by gomezzz** [comment]
> Is it clear now?

No, sorry, I don't get it. Can you post a code snippet (pseudocode or whatever) of what you would want to call and what it should do? And, then explain which specific changes in paseos would be required. What do you mean by 

>  I/O functionality

paseos should read some file? or parse some input strings etc.?

**Comment by johanos1** [comment]
What about now?

**Comment by gomezzz** [comment]
> What about now?

A bit more but I am trying to wrap my head around the practical implementation considerations. Couldn't you do this already by just writing a wrapper around the register and perform activity functions that can be called asynchronously, so the user could do this themselves depending on their needs? 

Because that may be a better way here because any additional mode of interaction we supply we need to support long-term. If people start using it, we cannot just drop it. So maybe, it would be better to just add an minimal example how to write such a wrapper instead of making it a core feature? 

It is, after all, already proving difficult to support running activities in notebook, scripts at the same time and if we want introduce any more complexity later adding this as well will make it only more difficult?
